authors: [kugick, sebcio98]
name: FarmLife
version: 0.1
main: net.kugick.FarmLife.FarmLife
commands:
  FarmLife:
    description: FarmLife plugin main command.
  MyFarm:
    description: MyFarm teleport commmand.
  Menu:
    description: FarmLife menu
